Repository plugwise/python-plugwise-usb, pull requests merged in 2023-12, with the labels that each got.

#109 Artifact needs to be one PR (not #104 and #105)
  .github/workflows/verify.yml
Labels: bug, dependencies

#112 Run actions in incoming PRs
  .github/workflows/verify.yml
Labels: bug

#111 Fix flooding of plugwise network by CircleEnergyCountersRequest (2nd try)
  plugwise_usb/nodes/circle.py
Labels: bug, enhancement, python

#116 Bump to v0.31.1 release-version
  pyproject.toml
Labels: enhancement

#117 Add badges
  README.md
Labels: documentation

#118 Further improvements to prevent flooding the network with CircleEnergyCountersRequests
  plugwise_usb/nodes/circle.py
Labels: bug
